spring:
  application:
    name: appointment-scheduling-api
    endpoints:
      password-reset-verify: "/user/password-reset/verify"
  profiles:
    active: ${SPRING_PROFILE:dev}

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: ${JWT_SECRET:thebigbrownfoxjumpsoverthelazydog}

firebase:
  project-id: ${FIREBASE_PROJECT_ID:}
  service-account-file: ${FIREBASE_CONFIG:}

brevo:
  api-key: ${BREVO_API_KEY:}
  from-email: ${BREVO_FROM_EMAIL:}
  from-name: ${BREVO_FROM_NAME:Gabay System}

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  frontend-url: http://localhost:5173
  endpoints:
    password-reset-verify: "/user/password-reset/verify"

password:
  reset:
    token:
      expiration:
        hours: 24

admin:
  default:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
    email: ${ADMIN_EMAIL:admin@guidance.edu}
  auto-create: true

appointment:
  max-pending-per-student: 1



