name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create Firebase credentials
        run: |
          mkdir -p src/main/resources
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > src/main/resources/firebase-service-account.json
          echo "Firebase file created"

      - name: Build Docker images
        run: docker compose build

      - name: Start containers in background
        run: docker compose up -d

      - name: Wait for application to start
        run: sleep 15

      - name: Check if containers are running
        run: docker compose ps

      - name: Check container logs
        run: docker compose logs

      - name: Stop containers
        run: docker compose down